import { BodyType } from './body-type.enum';
import { Car } from './car.interface';

export const MOCK_CARS: Car[] = [
  {
    id: 'car_001',
    brand: 'Mercedes-Benz',
    model: 'S-Class S580',
    year: 2024,
    mileage_km: 12500,
    body_type: BodyType.SEDAN,
    engine: { volume: '4.0L', type: 'V8', power_hp: 503 },
    color: 'Obsidian Black',
    interior_material: 'Nappa Leather',
    price_per_day_pln: 1800,
    is_available: true,
  },
  {
    id: 'car_002',
    brand: 'Porsche',
    model: '911 Carrera 4S',
    year: 2023,
    mileage_km: 8200,
    body_type: BodyType.COUPE,
    engine: { volume: '3.0L', type: 'Flat-6', power_hp: 450 },
    color: 'GT Silver Metallic',
    interior_material: 'Black Leather/Alcantara',
    price_per_day_pln: 2200,
    is_available: true,
  },
  {
    id: 'car_003',
    brand: 'BMW',
    model: 'X7 xDrive40i',
    year: 2024,
    mileage_km: 5400,
    body_type: BodyType.SUV,
    engine: { volume: '3.0L', type: 'Inline-6', power_hp: 380 },
    color: 'Mineral White',
    interior_material: 'Merino Leather',
    price_per_day_pln: 1500,
    is_available: true,
  },
  {
    id: 'car_004',
    brand: 'Audi',
    model: 'RS6 Avant',
    year: 2023,
    mileage_km: 15000,
    body_type: BodyType.SEDAN,
    engine: { volume: '4.0L', type: 'V8', power_hp: 600 },
    color: 'Nardo Grey',
    interior_material: 'Valcona Leather',
    price_per_day_pln: 1900,
    is_available: false,
  },
  {
    id: 'car_005',
    brand: 'Lamborghini',
    model: 'Urus',
    year: 2024,
    mileage_km: 3200,
    body_type: BodyType.SUV,
    engine: { volume: '4.0L', type: 'V8', power_hp: 650 },
    color: 'Giallo Auge',
    interior_material: 'Alcantara/Carbon',
    price_per_day_pln: 4500,
    is_available: true,
  },
  {
    id: 'car_006',
    brand: 'Range Rover',
    model: 'Autobiography',
    year: 2024,
    mileage_km: 6100,
    body_type: BodyType.SUV,
    engine: { volume: '4.4L', type: 'V8', power_hp: 530 },
    color: 'Santorini Black',
    interior_material: 'Semi-Aniline Leather',
    price_per_day_pln: 2500,
    is_available: true,
  },
  {
    id: 'car_007',
    brand: 'Ferrari',
    model: 'Roma',
    year: 2023,
    mileage_km: 4800,
    body_type: BodyType.COUPE,
    engine: { volume: '3.9L', type: 'V8', power_hp: 620 },
    color: 'Rosso Corsa',
    interior_material: 'Beige Tradizione',
    price_per_day_pln: 3800,
    is_available: true,
  },
  {
    id: 'car_008',
    brand: 'Bentley',
    model: 'Continental GT',
    year: 2024,
    mileage_km: 2100,
    body_type: BodyType.COUPE,
    engine: { volume: '6.0L', type: 'W12', power_hp: 635 },
    color: 'Midnight Emerald',
    interior_material: 'Portland Leather',
    price_per_day_pln: 3500,
    is_available: true,
  },
  {
    id: 'car_009',
    brand: 'Tesla',
    model: 'Model S Plaid',
    year: 2024,
    mileage_km: 9500,
    body_type: BodyType.SEDAN,
    engine: { volume: 'Electric', type: 'Tri-Motor', power_hp: 1020 },
    color: 'Ultra Red',
    interior_material: 'Vegan Leather',
    price_per_day_pln: 1400,
    is_available: true,
  },
  {
    id: 'car_010',
    brand: 'Aston Martin',
    model: 'DBX707',
    year: 2024,
    mileage_km: 1500,
    body_type: BodyType.SUV,
    engine: { volume: '4.0L', type: 'V8', power_hp: 707 },
    color: 'Aston Martin Racing Green',
    interior_material: 'Caithness Leather',
    price_per_day_pln: 3200,
    is_available: true,
  },
];
