name: CI Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: super_secret_password
          POSTGRES_DB: cars_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Prisma Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: 'postgresql://admin:super_secret_password@postgres:5432/cars_database?schema=public'

      - name: Run Unit & Integration Tests (with 60% Coverage check)
        run: yarn test --watchAll=false
        env:
          DATABASE_URL: 'postgresql://admin:super_secret_password@postgres:5432/cars_database?schema=public'

      - name: Run E2E Tests
        run: yarn test:e2e
        env:
          DATABASE_URL: 'postgresql://admin:super_secret_password@postgres:5432/cars_database?schema=public'
